# Generated by Django 4.2.1 on 2023-05-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitem',
            name='image',
        ),
    ]
